service:
  name: novel-to-trello

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  main:
    handler: main.fetchNovels
    timeout: 30
    events:
      - schedule: rate(30 minutes)